### ISSUE TITLE
[Question] Ant-v4 produces smooth joint angles but non-smooth joint torques (actions)

### ISSUE THREAD

**Issue by Omer1Yuval1** [Farama-Foundation/Gymnasium#546] opened 2023-06-08 13:34 UTC
### Question

I trained a PPO (SB3) agent for the `Ant-v4` environment using default settings (I used 100 steps per episode and a total of 20M steps). Training results and videos of the trained agent seem normal and similar to those reported in the literature and documentation (see [attached video](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/b8493a64-bcca-41b3-8e4c-6a84f63961aa
)).

However, when I plot joint angles and torques (i.e., actions) over time, joint angles are nice and smooth (as expected), but joint torques are not smooth and non-intuitive (i.e., it's difficult to imagine how these correlate with the resulting joint angles). This is shown in the attached plots for [1s](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/eb49c06c-b3d2-4470-b16e-6f13d58f3e99), [0.5s](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/b9a58e5d-faf2-4130-a60a-9f5fbe77b599), and [0.25s](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/5607defd-84e4-4d08-b789-fe787539e26b).

I was wondering if anyone has ever looked at this, and whether this behavior is expected. Also, do you think this has more to do with the RL algorithm or the physical model?

![ant_joint_angles_and_torques_T=1s](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/eb49c06c-b3d2-4470-b16e-6f13d58f3e99)
![ant_joint_angles_and_torques_T=0 5s](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/b9a58e5d-faf2-4130-a60a-9f5fbe77b599)
![ant_joint_angles_and_torques_T=0 25s](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/5607defd-84e4-4d08-b789-fe787539e26b)

**Comment by Omer1Yuval1** [comment] 2023-06-08 20:06
> 1\. Did you use `use_contact_forces=False` (which is the default)

Yes.

> 2\. can you run an episode of the policy and print total `info["reward_ctrl"]` and `info["reward_forward"]` and episode length

total_reward_ctrl: -91.2136555314064
total_reward_forward: 320.2852637357757
Number of steps: 100

> 3\. Did you use `frame_skip=1` (at least it looks like it)

I did not change it. It is hard coded as 5 in `Ant_v4.py`.
`MujocoEnv.__init__(self, xml_file, 5, observation_space=observation_space, default_camera_config=DEFAULT_CAMERA_CONFIG,
**kwargs,)`

> 4\. What does it mean by "joint torque (normalized)" what is "normalized"?

This refers to `ctrlrange="-1.0 1.0"` in `ant.xml`. It does not indicate any change to the default settings or any postprocessing of action values. Apologies for the confusion.

**Comment by Omer1Yuval1** [comment] 2023-06-09 05:49
@Kallinteris-Andreas there was a mistake in the plots. I updated them in my question. Sorry about that. I also added black dots to make it easier to see the discretization of the lines.

**Comment by pseudo-rnd-thoughts** [comment] 2023-06-09 10:42
@Omer1Yuval1 It is difficult to understand the figures, while it is easier to see all of the results, could you split each of the hips into 4 separate figures.

**Comment by Omer1Yuval1** [comment] 2023-06-09 13:59
@pseudo-rnd-thoughts How about this? It shows only two hips for which joint angles clearly undulate.

![ant_joint_angles_and_torques_T=1s_ hip_2,hip_4](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/2d94ed56-b0cb-4ea7-8458-d42fc31c0be6)

**Comment by Kallinteris-Andreas** [comment] 2023-06-09 14:31
1. The x-axis (time) of your graphs are wrong, the default `dt` for `Ant-v4` is 0.05 (which is the duration a torque force will be applied)
2. can you plot the angles/tongues of this expert policy: https://github.com/Kallinteris-Andreas/gymnasium-robotics-mujuco-v5-envs-validation/blob/main/results/ant_v4_fixed_without_ctn_TD3/run_0/best_model.zip
```py
from stable_baselines3 import TD3, PPO
model = TD3.load(path='./ant_v4_fixed_without_ctn_TD3/run_0/best_model.zip', env=eval_env, device='cpu')
```

**Comment by pseudo-rnd-thoughts** [comment] 2023-06-09 16:11
@Omer1Yuval1 Is there a reason why we expect the torque to have a smooth curve like the angles

**Comment by Omer1Yuval1** [comment] 2023-06-15 08:21
> 1. The x-axis (time) of your graphs are wrong, the default `dt` for `Ant-v4` is 0.05 (which is the duration a torque force will be applied)

@Kallinteris-Andreas After having another look at my code, I think this is related to the way I evaluated the policy and stored observations and actions (which I then export to csv files and plot). Can you please confirm that the code below is correct for evaluating the policy and storing observations and actions? Note that in this new code I still store actions every step, but I set them to zero whenever an action is not taken by the environment.
```
qpos = np.array([])
actions = np.array([])
terminated = 0
truncated = 0
while(not terminated and not truncated):
    action, _states = model.predict(obs)
    for j in range(env.frame_skip):
        obs, reward, terminated, truncated, info = env.step(action)
        
        qpos = np.append(qpos, info["qpos"])
        
        if(j == 0):
            actions = np.append(actions, action)
        else:
            actions = np.append(actions, np.zeros(len(action)))
        
env.close()
```

> 2. can you plot the angles/tongues of this expert policy: https://github.com/Kallinteris-Andreas/gymnasium-robotics-mujuco-v5-envs-validation/blob/main/results/ant_v4_fixed_without_ctn_TD3/run_0/best_model.zip (it gets 6k+ return over 1000 steps)

@Kallinteris-Andreas Sure. I'll post a separate comment once I have it. Could you please share a similar plot for `Ant-v4` (or just the raw data for observations and actions) so we can have a ground truth to compare to?

> Is there a reason why we expect the torque to have a smooth curve like the angles
Is this a bug or just unexpected thing?

@pseudo-rnd-thoughts that's a good question. I'd say it's an unexpected result, not a bug. To my understanding, when we simulate mechanical models inspired by animals, we either want to learn about the animal, or use principles from the animal to implement in robots. In both cases, we might be interested in different levels of abstraction and different details at each level. This might include body geometry, anatomy and mechanics, muscle mechanics and control, and/or neural dynamics. It might also include sensory feedback and proprioception (typically encoded implicitly in RL as part of the observation space).

Regarding the smoothness of joint torques
- From the biological point of view, this mostly depends on muscle intrinsic dynamics, and even if not smooth (such as in the case of action potentials), we would still expect an (almost) in-phase positive correlation between muscle activation, muscle contraction, and joint actuation. Although in `ant.xml` joint mechanics is much simpler, I find it surprising and non-intuitive that joint torques are so irregular and almost look random compared to joint angles.
- From the robotics point of view, I am not an expert, but I would imagine we would prefer to actuate controllers in a smooth manner as much as possible, to protect both the controller and the robot from unnecessary vibration, wear and energy loss.

I think it's important to make the distinction between the optimization algorithm, joint mechanics, and actuator dynamics. My feeling is that the torque profiles that I get are optimal for the given mechanical constraints. However, I might be wrong, which is why I wanted to check this with you. I think the plots I've attached show useful and important metrics for model evaluation and validation. I suggest including such quantitative data in the documentation page, for people to know what to expect when training these environments. I also suggest to include `qpos`, `qvel` and `action` in `info` in the step function, in order to make them more accessible for such analyses.

**Comment by pseudo-rnd-thoughts** [comment] 2023-06-15 13:02
As this is not a bug, I'm closing the issue. 
Part of this issue is that the MuJoCo environment is not intended to implement robots or to simulate animals correctly. The environment was initially developed to implementation to showcase the possible performance of RL algorithms for robots without the intention of taking the robot to the real world.

**Closed by pseudo-rnd-thoughts** 2023-06-15 13:02 UTC
Labels: question

**Comment by Omer1Yuval1** [comment] 2023-06-15 16:24
> 2\. can you plot the angles/tongues of this expert policy: https://github.com/Kallinteris-Andreas/gymnasium-robotics-mujuco-v5-envs-validation/blob/main/results/ant_v4_fixed_without_ctn_TD3/run_0/best_model.zip (it gets 6k+ return over 1000 steps)
> 
> ```python
> from stable_baselines3 import TD3, PPO
> model = TD3.load(path='./ant_v4_fixed_without_ctn_TD3/run_0/best_model.zip', env=eval_env, device='cpu')
> ```

@Kallinteris-Andreas I am getting this error when trying to load the model (using the `Ant-v4` env).
```
Action space: Box(-1.0, 1.0, (8,), float32)
Obs space: Box(-inf, inf, (27,), float64)
Traceback (most recent call last):
  File "---", line 122, in <module>
    main()
  File "---", line 53, in main
    model = TD3.load(path=model_file, env=env, device='cpu')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "---\stable_baselines3\common\base_class.py", line 706, in load
    raise KeyError("The observation_space and action_space were not given, can't verify new environments")
KeyError: "The observation_space and action_space were not given, can't verify new environments"
```

**Comment by Kallinteris-Andreas** [comment] 2023-06-15 16:50
```
qpos = np.array([])
actions = np.array([])
terminated = 0
truncated = 0
while(not terminated and not truncated):
    action, _states = model.predict(obs)
        obs, reward, terminated, truncated, info = env.step(action)
        qpos = np.append(qpos, info["qpos"])
        
        actions = np.append(actions, action)
        
env.close()
```
1) do not need to loop over frame skips (this is done internally in `mujoco_step()`)
2) pretty sure `info["qpos"]` does not exist, not sure how you get it

**Comment by Omer1Yuval1** [comment] 2023-06-16 07:03
Thanks @Kallinteris-Andreas, it worked with `pip install numpy==1.24.3`.

> 2. pretty sure `info["qpos"]` does not exist, not sure how you get it

I modified the environment to include `action`, `qpos` and `qvel` in `info`, which I then export to csv files and plot. I recommend including them in future versions to make them more accessible for such analyses.

> 1. do not need to loop over frame skips (this is done internally in `mujoco_step()`)

The reason I included the inner loop is to get joint angles for the steps for which actions are skipped. For these I set `action` to zero and store them in my `actions` csv in order to have matching rows (one per time step). If `obs` is already given after `frame_skip` frames each time we call `step()`, how can I get joint angles in every frame?

**Comment by Kallinteris-Andreas** [comment] 2023-06-16 07:58
There are no "skipped" actions, the control action is thought the whole step duration (`env.dt`)

**Comment by Omer1Yuval1** [comment] 2023-06-16 08:20
Okay, thanks @Kallinteris-Andreas , I think I get it now.

> 3. Did you use `frame_skip=1` (at least it looks like it)

You said it looks like I am using `frame_skip=1` although I was using the default (5). I thought that action resolution (black dots in my plot) made you think that, and then I suspected it might have something to do with my code for evaluating the policy. Can you please clarify this? What would you expect it to look like for `frame_skip=5`?

**Comment by Kallinteris-Andreas** [comment] 2023-06-16 08:31
i expect the duration of an action to be `env.dt` (0.05 in the case of Ant not 0.01)

**Comment by Omer1Yuval1** [comment] 2023-06-16 13:56
> i expect the duration of an action to be `env.dt` (0.05 in the case of Ant not 0.01)

So if you run the code below for an environment with an episode length of 100 steps and `frame_skip=5`, you expect to have only 20 iterations in the while loop?
```
terminated = 0
truncated = 0
while(not terminated and not truncated):
    action, _states = model.predict(obs)
    obs, reward, terminated, truncated, info = env.step(action)
env.close()
```

**Comment by Omer1Yuval1** [comment] 2023-06-16 14:13
> If you use the argument `max_episode_lenght=100` (using the timelimit wrapper) then you expect it to truncate in 100 steps

Which still correspond to 5 episodes (for `frame_skip=5`)? I am using the `RecordVideo` wrapper.

**Comment by Kallinteris-Andreas** [comment] 2023-06-16 14:16
No, `frame_skip` just changes the `env.dt` nothing else

**Comment by Omer1Yuval1** [comment] 2023-06-16 14:27
So I run the policy for 100 steps and get 100 actions back (black dots in my plot). Why is this not expected? What am I missing?

**Comment by Kallinteris-Andreas** [comment] 2023-06-16 15:04
Then the total duration should be 0.05 x 100 = 5 sec (with each step lasting for 0.05)

**Comment by Omer1Yuval1** [comment] 2023-06-16 15:13
I see, so the problem in my plots is just scaling. I am showing 1s but it is actually 5s.

**Comment by Omer1Yuval1** [comment] 2023-06-20 12:55
> 2\. can you plot the angles/tongues of this expert policy: https://github.com/Kallinteris-Andreas/gymnasium-robotics-mujuco-v5-envs-validation/blob/main/results/ant_v4_fixed_without_ctn_TD3/run_0/best_model.zip (it gets 6k+ return over 1000 steps)
> 
> ```python
> from stable_baselines3 import TD3, PPO
> model = TD3.load(path='./ant_v4_fixed_without_ctn_TD3/run_0/best_model.zip', env=eval_env, device='cpu')
> ```

@Kallinteris-Andreas I attached below the plots for best_model.zip. For 100 steps I got `total_reward_forward≈500`, and `total_reward_ctrl≈-80`.


![ant_joint_angles_and_torques_T=2s](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/e00b94ec-7f79-4b61-8867-dd09ae4df101)

![ant_joint_angles_and_torques_T=2s_ hip_2,hip_4](https://github.com/Farama-Foundation/Gymnasium/assets/35100851/0e039285-d692-428b-8696-632dddd03ae8)
