### ISSUE TITLE
[Bug Report] flatten space raise NotImplementedError(f"Unknown space: `{space}`")

### ISSUE THREAD

**Issue by PatrickYanZ** [Farama-Foundation/Gymnasium#311] opened 2023-02-05 16:32 UTC
### Describe the bug

Hello all, I am facing the issues as below. I am confusing about `NotImplementedError: Unknown space: Box(-inf, inf, (5, 5), float32)`. I ultilizing the flatten observation spaces. I do not know `Box(-inf, inf, (5, 5), float32)` is unknown. This should be recognized in the spaces I defined.

```
Traceback (most recent call last):
  File "I:\Research\tcom paper\MO-Gymnasium\tests\test_highway.py", line 44, in <module>
    wrapped_obs, wrapped_obs_info = wrapped_env.reset()
  File "D:\Users\yanzi\miniconda3\lib\site-packages\gymnasium\core.py", line 416, in reset
    return self.observation(obs), info
  File "D:\Users\yanzi\miniconda3\lib\site-packages\gymnasium\wrappers\flatten_observation.py", line 41, in observation
    return spaces.flatten(self.env.observation_space, observation)
  File "D:\Users\yanzi\miniconda3\lib\functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "D:\Users\yanzi\miniconda3\lib\site-packages\gymnasium\spaces\utils.py", line 155, in flatten
    raise NotImplementedError(f"Unknown space: `{space}`")
NotImplementedError: Unknown space: `Box(-inf, inf, (5, 5), float32)`
```

The small debug script I rewrite based on highway_env works fine. In single episode, the box property was recognized successfully. 
https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L178
```
import gymnasium.spaces as spaces
import numpy as np
from gymnasium.spaces import Box
from gymnasium.spaces.utils import flatten_space, flatten

box = Box(0.0, 1.0, shape=(3, 4, 5))

print(box)

box = flatten_space(box)

print(box)

vehicles_count = 5
len_features = 5
highway_space = spaces.Box(shape=(vehicles_count, len_features), low=-np.inf, high=np.inf, dtype=np.float32)

print(highway_space)
highway_space = flatten_space(highway_space)
print(highway_space)

vehicles_count = 5
len_features = 5
highway_space = Box(shape=(vehicles_count, len_features), low=-np.inf, high=np.inf, dtype=np.float32)

print(highway_space)
highway_space = flatten_space(highway_space)
print(highway_space)

print(flatten(highway_space, highway_space.sample()))
```

But, when I run this in multiple episodes, like the code example I attached, problems are raised. I check the root fault is not on mo_gymnasium. I suspect that, the observation space of highway_env (https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L178) is unrecognized as Box. 

Appreciate in advance.

### Code example

```shell
import gymnasium.spaces as spaces
import numpy as np
from gymnasium.spaces import Box
from gymnasium.spaces.utils import flatten_space, flatten
import gymnasium
# import gymnasium
import mo_gymnasium as mo_gym
from gymnasium import spaces
from gymnasium.wrappers import FlattenObservation

box = Box(0.0, 1.0, shape=(3, 4, 5))

print(box)

box = flatten_space(box)

print(box)

vehicles_count = 5
len_features = 5
highway_space = spaces.Box(shape=(vehicles_count, len_features), low=-np.inf, high=np.inf, dtype=np.float32)

print(highway_space)
highway_space = flatten_space(highway_space)
print(highway_space)

vehicles_count = 5
len_features = 5
highway_space = Box(shape=(vehicles_count, len_features), low=-np.inf, high=np.inf, dtype=np.float32)

print(highway_space)
highway_space = flatten_space(highway_space)
print(highway_space)

print(flatten(highway_space, highway_space.sample()))

print(gymnasium.__version__)


env = mo_gym.make("mo-highway-fast-v0")
wrapped_env = FlattenObservation(env)
obs, info = env.reset()
print(obs,info)
wrapped_obs, wrapped_obs_info = wrapped_env.reset()
print(wrapped_obs, wrapped_obs_info)
```

### System info

pip install gymnasium
```
git clone https://github.com/Farama-Foundation/MO-Gymnasium
cd MO-Gymnasium
pip install -e .
```
gymnasium == 0.27.1

Windows 11: Anaconda

Python == 3.9.5

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment] 2023-02-05 17:49
Hi, I believe that the issue is rather than mo-gymnasium rather than gymnasium itself. Therefore Im going to close the issue here and could you reopen on https://github.com/farama-Foundation/mo-gymnasium

My suspicion is that as highway-env has not updated to gymnasium then the type is actually a gym Box not a gymnasium Box therefore issues happen.

**Closed by pseudo-rnd-thoughts** 2023-02-05 17:49 UTC
Labels: bug

**Comment by LucasAlegre** [comment] 2023-02-05 20:51
Fixed in https://github.com/Farama-Foundation/MO-Gymnasium/pull/33
