### ISSUE TITLE
[Question] AsyncVectorEnv "set_attr" not working as expected

### ISSUE THREAD

**Issue by FabioRaff** [Farama-Foundation/Gymnasium#357] opened 2023-03-04 23:47 UTC
### Question

I am trying to change the "goal" attribute of "FetchPickAndPlace-v2" (from gymnasium-robotics) using AsyncVectorEnv but it is not working as expected.

Code example:

```python
envs = gym.vector.make('FetchPickAndPlace-v2', num_envs=2)
actions = [[0, 0, 0, 0], [0, 0, 0, 0]]
new_goals = [[1, 1, 1], [1, 1, 1]]

obs, _ = envs.reset()
print(obs['desired_goal']) 
>>> [[1.28639574 0.69880261 0.42469975], [1.37864519 0.71064809 0.42469975]]

envs.set_attr('goal', new_goals)
```

if I check:

```python
print(envs.get_attr('goal'))
>>> ([1, 1, 1], [1, 1, 1])
```

it correctly prints the newly assigned goals, but after a step, the "desired_goals" key of the obs (which is simply self.goal attribute from the env) does not show the updated goals and rewards are also not calculated for the new goals:

```python
obs, rew, _, _, _ = envs.step(actions)
print(obs['desired_goal'])
>>> [[1.28639574 0.69880261 0.42469975], [1.37864519 0.71064809 0.42469975]]
```

Am I doing something wrong? How can I change instance attributes of vector environments?

_______
OS: Ubuntu 20.04
Python 3.7
gymnasium 0.27.1
gymnasium_robotics 1.2.0

**Comment by pseudo-rnd-thoughts** [comment] 2023-03-05 00:28
Ok, this is a really interesting problem

I can replicate this issue in the single agent case which is easier to understand
```python
env = gym.make("FetchPickAndPlace-v2")
print(env.unwrapped)
action = np.array([0, 0, 0, 0])
new_goal = np.array([1, 1, 1])

obs, _ = env.reset()
print(f'{obs["desired_goal"]=}')

print(f'pre-set {env.goal=}')
env.goal = new_goal
print(f'post-set {env.goal=}')

obs, _, _, _, _ = env.step(action)
print(f'{obs["desired_goal"]=}')
```

The problem is that an environment created from `make` is actually wrapped by several wrappers
```python
print(env)
>>> <TimeLimit<OrderEnforcing<PassiveEnvChecker<MujocoFetchPickAndPlaceEnv<FetchPickAndPlace-v2>>>>>
```

So when we do `env.goal = ` we are not actually set the variable on the "base" environment, in this case, fetch pick and place but on the time limit. You can see this with
```python 
print(f'{env.goal=}, {env.env.goal=}')
>>> env.goal=array([1, 1, 1]), env.env.goal=array([1.34614611, 0.82321155, 0.42469975])
```

Why this is happening ... Im not sure. I think this is something unique in fetch pick and place but Im not sure. 
@RedTachyon or @rodrigodelazcano Any ideas?

**Comment by pseudo-rnd-thoughts** [comment] 2023-03-05 00:57
This seems like a fairly major bug, Im not sure how no idea has caught this before.

Using this simple testing example
```python
env = gym.make("CartPole-v1")
print(env)
env.reset()
print(env.gravity)
# 9.8
env.gravity = 1
print(env.gravity, env.env.gravity, env.unwrapped.gravity)
# 1 1 1
```

**Comment by FabioRaff** [comment] 2023-03-05 10:43
@pseudo-rnd-thoughts thanks for the quick response and explanation. I've tried the proposed fix but I get:

```
File "/home/fabioubu/miniconda3/envs/master/lib/python3.7/site-packages/gymnasium/core.py" line 272, in __getattr__
    raise AttributeError(f"accessing private attribute '{name}' is prohibited")
AttributeError: accessing private attribute '_has_reset' is prohibited
```

I can bypass it by removing the private attribute check in `Wrapper.__getattr__` but I guess that's not the way to do it...

**Comment by pseudo-rnd-thoughts** [comment] 2023-03-05 12:04
The proposed implementation is wrong. I realised before sleeping that the issue is much more complex to solve than I originally thought.

There are several cases that we need to consider for this
1. The variable is already defined in the wrapper, updated it
2. "env" is not defined in the wrapper, assign the variable in the wrapper
3. the variable is defined in one of the sub-environments `env`, assigned to the `env` with the variable defined
4. otherwise, assign in the wrapper

The problem is that in 3 we need to check the environment (and if that is a wrapper, its sub-environment, etc) before we run 4.

**Comment by pseudo-rnd-thoughts** [comment] 2023-08-22 11:05
Solved in https://github.com/Farama-Foundation/Gymnasium/pull/681

**Closed by pseudo-rnd-thoughts** 2023-08-22 11:05 UTC
Labels: question
