### ISSUE TITLE
[Proposal] Update cython dependency to cython 3

### ISSUE THREAD

**Issue by evan0greenup** [Farama-Foundation/Gymnasium#921] opened 2024-02-13 07:55 UTC
### Proposal

Currently, the dependency specifier on `cython` is `cython < 3`.  It would be good to port `gymnasium` to cython 3. 

### Motivation

User whose project need both cython 3 and gymnasium would have problem. And cython 3 fix a lot of bugs.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment] 2024-02-13 08:08
`cython<3` to use the old `mujoco-py` binaries for the `v2` and `v3` of those requirements, if you are not using them you can safely use `cython>=3`

**Comment by im-Kitsch** [comment] 2024-02-28 13:22
I think we all admit that mujoco-py and mujoco-series "-v2" environments are annoying and not as good as new version. But the problem is that they are still widely used since the research cummunity still uses mujoco-py frequently for online or offline RL.  To validate this, just search RL related paper randomly in this year or check the new issues in mujoco-py repo. To compare with new/old baselines/benchmarks people have to use old "-v2" version.

Moreover, the dependency for cython could be simplely updated by this PR https://github.com/openai/mujoco-py/pull/782. So it would be really really very very appreciated to adjust mujoco-py to cython>3. 

I disklike Mujoco-py, it's really annoying but I think many people still have to use it for a long time.

**Comment by pseudo-rnd-thoughts** [comment] 2024-02-28 13:56
Mujoco-py is hosted and maintained by OpenAI, not Farama, therefore, there is nothing that we can do to apply the PR you link above. 
We understand your annoyance with v2 and plan to remove them in the future but this isn't a problem and if you don't download `gymnasium[mujoco-py]` then this issue shouldn't effect you

**Comment by pseudo-rnd-thoughts** [comment] 2024-04-04 14:58
Only "gymnasium[mujoco-py]" is limited to `cython < 3`, therefore, for users needing cython 3 then they cannot use mujoco-py (from pypi) or must build from source with the linked solution. 
Therefore, closing as not a gymnasium issue

**Closed by pseudo-rnd-thoughts** 2024-04-04 14:58 UTC
Labels: enhancement
